---
- name: Install/configure PCP on various hosts
  hosts: pcp-hosts
  gather_facts: false
  vars:
    # Services to be enabled/started
    enable_services: 
      - pmcd
      - pmlogger
    
    # The subnets or ranges of hosts allowed to connect to clients to fetch info
    remote_subnets:
      - 10.0.*
      - 192.168.5.10

    # Enable any additional agents
    # pmda_extras:
    #   - jbd2  
    #   - kvm
    #   - linux
    #   - mmv
    #   - overhead
    #   - pipe
    #   - pmcd
    #   - proc
    #   - root
    #   - xfs
    #   - zfs
  tasks:
  # dnf install required pcp packages
  - name: Install pcp packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop:
      - pcp
      - pcp-system-tools

#   - name: Configure the pmcd process(add all of the allowed subnets)
#     ansible.builtin.blockinfile:
#       path: /etc/pcp/pmcd/pmcd.conf
#       block: |
#         allow hosts {{ item }} : fetch;
# #      marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
#     loop: "{{ remote_subnets }}"
#       # - { name: host1, ip: 10.10.1.10 }
#       # - { name: host2, ip: 10.10.1.11 }
#       # - { name: host3, ip: 10.10.1.12 }

  - name: Configure the pmcd process(add all of the allowed subnets)
    ansible.builtin.lineinfile:
      path: /etc/pcp/pmcd/pmcd.conf
      line: "allow hosts {{ item }} : fetch;"
      insertafter: '[access]'
      insertbefore: 'disallow.*'
    loop: "{{ remote_subnets }}"

  - name: Start and enable pcp services
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: true
    loop: "{{ enable_services }}"
      

  # configure pcp on host
