---
- name: Install/configure PCP on various hosts
  hosts: pcp-hosts
  gather_facts: false
  vars:
    # Services to be enabled/started
    enable_services: 
      - pmcd
      - pmlogger
    
    # The subnets or ranges of hosts allowed to connect to clients to fetch info
    remote_subnets:
      - 10.0.*
#      - 192.168.5.10
#      - 1.1.1.1

    # Enable any additional agents
    # pmda_extras:
    #   - jbd2  
    #   - kvm
    #   - linux
    #   - mmv
    #   - overhead
    #   - pipe
    #   - pmcd
    #   - proc
    #   - root
    #   - xfs
    #   - zfs
  tasks:
  # dnf install required pcp packages
  - name: Install pcp packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop:
      - pcp
      - pcp-system-tools

  - name: Configure the pmcd process(add all of the allowed subnets)
    ansible.builtin.blockinfile:
      path: /etc/pcp/pmcd/pmcd.conf
      block: "{{ lookup('ansible.builtin.template', 'pmcd-access.j2') }}"
      insertafter: "\\[access\\]"

  # - name: Configure the pmcd process(add all of the allowed subnets)
  #   ansible.builtin.lineinfile:
  #     path: /etc/pcp/pmcd/pmcd.conf
  #     line: "allow hosts {{ item }} : fetch;"
  #     # insertafter: '[access]'
  #     firstmatch: true
  #     insertbefore: 'disallow.*'
  #   loop: "{{ remote_subnets }}"

  - name: Enable pmcd listening ports on firewall
    ansible.posix.firewalld:
      port: 44321/tcp
      permanent: true
      immediate: true
      state: enabled
    ignore_errors: false

  - name: Enable selinux for pmcd
    ansible.builtin.shell: setsebool -P pcp_bind_all_unreserved_ports on
    ignore_errors: true

  - name: Start and enable pcp services
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: true
    loop: "{{ enable_services }}"
