---
- name: Install/configure PCP on various hosts
  hosts: pcp-hosts
  gather_facts: false
  vars:
    # Services to be enabled/started
    enable_services: 
      - pmcd
      - pmlogger
    
    # Enable any additional agents
    # pmda_extras:
    #   - jbd2  
    #   - kvm
    #   - linux
    #   - mmv
    #   - overhead
    #   - pipe
    #   - pmcd
    #   - proc
    #   - root
    #   - xfs
    #   - zfs
  tasks:
  # dnf install required pcp packages
  - name: Install pcp packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop:
      - pcp
      - pcp-system-tools

  - name: Start and enable pcp services
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: true
    loop: "{{ enable_services }}"
      

  # configure pcp on host
